//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medinlinea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public int IdCita { get; set; }
        public string NombrePac { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> FechaNacimientoPac { get; set; }
        public string EmailPac { get; set; }
        public string MensajeCita { get; set; }
        public string Imagen1 { get; set; }
        public string Imagen2 { get; set; }
        public string Imagen3 { get; set; }
        public string Imagen4 { get; set; }
        public Nullable<int> IdEspecialista { get; set; }
        public string TelefonoPac { get; set; }
    
        public virtual Especialistas Especialistas { get; set; }
    }
}
