//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medinlinea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudades
    {
        public Ciudades()
        {
            this.Direcciones = new HashSet<Direcciones>();
        }
    
        public int IdCiudad { get; set; }
        public string NombreCiudad { get; set; }
    
        public virtual ICollection<Direcciones> Direcciones { get; set; }
    }
}
