//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medinlinea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direcciones
    {
        public int IdDireccion { get; set; }
        public string Pais { get; set; }
        public string Area { get; set; }
        public string Calle { get; set; }
        public string TelefonoFijo { get; set; }
        public Nullable<int> IdEspecialista { get; set; }
        public Nullable<int> IdCiudad { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
    
        public virtual Especialistas Especialistas { get; set; }
        public virtual Ciudades Ciudades { get; set; }
    }
}
