//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medinlinea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especialistas
    {
        public Especialistas()
        {
            this.Articulos = new HashSet<Articulos>();
            this.Citas = new HashSet<Citas>();
            this.Direcciones = new HashSet<Direcciones>();
            this.Estadisticas = new HashSet<Estadisticas>();
            this.Publicidades = new HashSet<Publicidades>();
        }
    
        public int IdEspecialista { get; set; }
        public string NombreEsp { get; set; }
        public string ApellidoEsp { get; set; }
        public string FotoEsp { get; set; }
        public string PaginaWebEsp { get; set; }
        public string EmailEsp { get; set; }
        public string CelularEsp { get; set; }
        public Nullable<int> Calificacion { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public Nullable<int> IdCurriculum { get; set; }
        public Nullable<int> IdSuscripcion { get; set; }
        public Nullable<int> IdLogin { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual ICollection<Articulos> Articulos { get; set; }
        public virtual ICollection<Citas> Citas { get; set; }
        public virtual Curriculums Curriculums { get; set; }
        public virtual ICollection<Direcciones> Direcciones { get; set; }
        public virtual Especialidades Especialidades { get; set; }
        public virtual Membresias Membresias { get; set; }
        public virtual ICollection<Estadisticas> Estadisticas { get; set; }
        public virtual ICollection<Publicidades> Publicidades { get; set; }
        public virtual Login Login { get; set; }
    }
}
