//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medinlinea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoUsuario
    {
        public TipoUsuario()
        {
            this.Login = new HashSet<Login>();
        }
    
        public int IdTipoUsuario { get; set; }
        public string NombreTipoUsuario { get; set; }
    
        public virtual ICollection<Login> Login { get; set; }
    }
}
