//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medinlinea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chats
    {
        public long id { get; set; }
        public string nombre { get; set; }
        public string mensaje { get; set; }
        public string tipo_usuario { get; set; }
        public System.DateTime fecha_creacion { get; set; }
    }
}
