//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medinlinea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curriculums
    {
        public Curriculums()
        {
            this.Especialistas = new HashSet<Especialistas>();
        }
    
        public int IdCV { get; set; }
        public string ImagenCV { get; set; }
        public string DescripcionCV { get; set; }
    
        public virtual ICollection<Especialistas> Especialistas { get; set; }
    }
}
