//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medinlinea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public Login()
        {
            this.Especialistas = new HashSet<Especialistas>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int IdLogin { get; set; }
        public string UsuarioLogin { get; set; }
        public string PasswordLogin { get; set; }
        public Nullable<int> IdTipoUsuario { get; set; }
    
        public virtual ICollection<Especialistas> Especialistas { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
