//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medinlinea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membresias
    {
        public Membresias()
        {
            this.Especialistas = new HashSet<Especialistas>();
        }
    
        public int IdMembresia { get; set; }
        public string TipoMembresia { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<Especialistas> Especialistas { get; set; }
    }
}
