//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medinlinea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicidades
    {
        public int IdPublicidad { get; set; }
        public string TipoPublicidad { get; set; }
        public string ImagenPub { get; set; }
        public Nullable<int> CantidadClicks { get; set; }
        public Nullable<int> IdMedico { get; set; }
    
        public virtual Especialistas Especialistas { get; set; }
    }
}
